### ISSUE TITLE
Jenkins Release task

### ISSUE THREAD

**Issue by tempvchitti** [allegro/axion-release-plugin#100]
Hi
I am executing release task on jenkins, but am getting this error

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':release'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:158)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:103)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:102)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.ajoberstar.grgit.exception.GrgitException: Problem pushing to remote.
	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy:117)
	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
	at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:188)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.callPush(GitRepository.groovy:93)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.this$2$callPush(GitRepository.groovy)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository$this$2$callPush$0.callCurrent(Unknown Source)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.push(GitRepository.groovy:88)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository$push.callCurrent(Unknown Source)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.push(GitRepository.groovy:84)
	at pl.allegro.tech.build.axion.release.domain.scm.ScmRepository$push$4.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.infrastructure.GradleAwareScmService.push(GradleAwareScmService.groovy:34)
	at pl.allegro.tech.build.axion.release.domain.scm.ScmService$push$1.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.domain.Releaser.pushRelease(Releaser.groovy:54)
	at pl.allegro.tech.build.axion.release.domain.Releaser$pushRelease$1.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.ReleaseTask.release(ReleaseTask.groovy:16)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
Caused by: org.eclipse.jgit.api.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:79)
	at java_util_concurrent_Callable$call$0.call(Unknown Source)
	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy:114)
	... 93 more
Caused by: org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1197)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	... 96 more

BUILD FAILED

Total time: 12.392 secs
Build step 'Invoke Gradle script' changed build result to FAILURE
Build step 'Invoke Gradle script' marked build as failure
Finished: FAILURE

Can someone point me please.

Thanks

**Comment by adamdubiel** [comment]
Hm, this:

`org.eclipse.jgit.api.errors.TransportException: Nothing to push.`

might be somethign useful, but should not happen in general. Can you show me some configuration or how you run the task?

**Comment by tempvchitti** [comment]
On jenkins, I have configured the github user and am using release as task. 

Also, I tested with same build script locally and was able to create a tag successfully. The only difference is am passing ssh key as secret key locally.

**Comment by adamdubiel** [comment]
Are you able to ssh onto the agent thats been running the job and `cd` to build files to see how does the repository look? Has the tag been created etc.

**Comment by tempvchitti** [comment]
yes when i checked on company github,i see the tag created

**Comment by adamdubiel** [comment]
Oh, so you can see that the tag has been pushed anyway? Can you show me the command that you are running?

**Comment by tempvchitti** [comment]
locally i just use, gradle release command
But on jenkins, what i dont understand is why there is an eclipse call

org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)

**Comment by adamdubiel** [comment]
Okay, so back to the beginning: you see the tag when running command locally, but can you see it when running Jenkins job? If not, can you `ssh` onto Jenkins agent and see build directory, if the tag has been created locally?

As to the "eclipse call" - `jgit` library is maintained by Eclipse Foundation, so it's in their namesapce.

**Comment by tempvchitti** [comment]
i dont see any tag created on jenkins job when I run the command with 'release' task , i get the above exception.
I cannot do ssh onto jenkins as access is restricted to developers.

Actually, there are two things I want to tell you. Locally, when I run release task from eclipse I get invalid security exception. But, when I goto command prompt and traverse to the project folder and run gradle release it works as expected. I think there is some issue with jgit library , just a guess.

**Comment by adamdubiel** [comment]
Okay, i don't think i can do much without some logs from Jenkins. I know CIs behave weirdly sometimes and it's hard to debug them without some kind of access (either by inserting "debug" statements like `git tag` in the task itself or using direct access). Can you ask developers to access this kind of data? Or change your build plan and insert `git tag` before calling release and after (make it a non-failing task).

As to the other thing - i don't know about Eclipse much, i use `gradle` only from command line (and InetlliJ for coding).

**Comment by tempvchitti** [comment]
ok, will try to get some logs tomorrow. 

Thank you for your support , much appreciated.

**Comment by adamdubiel** [comment]
No problem :) You could also show me the configuration of Jenkins job (including repository settings, excluding any thing that you might consider sensitive) so i could try and reproduce it locally, but i don't know if it will occur in my setup.

**Comment by tempvchitti** [comment]
Yesterday, i was able to push the tag to git repository. The issue was on jenkins the user which we used to connect to git does not have permissions to write.

**Comment by adamdubiel** [comment]
Meaning i can close this issue? :)

**Comment by tempvchitti** [comment]
yes. Thanks.

This plugin is great.

**Comment by adamdubiel** [comment]
Glad to hear it :)
