### ISSUE TITLE
MissingPropertyException: No such property: style for class: pl.allegro.tech.build.axion.release.infrastructure.git.GitChangesPrinter

### ISSUE THREAD

**Issue by janbols** [allegro/axion-release-plugin#160]
When doing a `gradle release` using the latest version of the plugin 1.4.0 and there's an uncommitted change, the plugin fails due to a wrong method call in `GitChangesPrinter`. 

`Caused by: groovy.lang.MissingPropertyException: No such property: style for class: pl.allegro.tech.build.axion.release.infrastructure.git.GitChangesPrinter
        at pl.allegro.tech.build.axion.release.infrastructure.git.GitChangesPrinter$_printChangeset_closure1.doCall(GitChangesPrinter.groovy:38)
        at pl.allegro.tech.build.axion.release.infrastructure.git.GitChangesPrinter.printChangeset(GitChangesPrinter.groovy:38)
        at pl.allegro.tech.build.axion.release.infrastructure.git.GitChangesPrinter.printChangeType(GitChangesPrinter.groovy:31)
        at pl.allegro.tech.build.axion.release.infrastructure.git.GitChangesPrinter.printChanges(GitChangesPrinter.groovy:25)
        at pl.allegro.tech.build.axion.release.domain.scm.ScmChangesPrinter$printChanges.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.VerifyReleaseTask.verify(VerifyReleaseTask.groovy:32)`

I saw this was already fixed in the current version on the development branch but not in the master branch (https://github.com/allegro/axion-release-plugin/blob/development/src/main/groovy/pl/allegro/tech/build/axion/release/infrastructure/git/GitChangesPrinter.groovy)

**Comment by adamdubiel** [comment]
Oh, i'm doing the emergency fi for this. Actually the `development` was way behind the master and it would not work with Gradle 1.4. I'm testing the fix right now and going to publish `1.4.1`.

**Comment by adamdubiel** [comment]
PR: https://github.com/allegro/axion-release-plugin/pull/161

**Comment by adamdubiel** [comment]
Closed by #161 (includes e2e test), released in `1.4.1`. Thanks for finding this issue :)

**Comment by janbols** [comment]
Thanks for the swift response!!!
