### ISSUE TITLE
Non-existing ReleaseFailedException constructor gets called on unsuccessful push

### ISSUE THREAD

**Issue by cliffred** [allegro/axion-release-plugin#222]
When a ScmPushResult is not successful, a `new ReleaseFailedException(result.remoteMessage)` is thrown. But remoteMessage is of type Optional\<String\> and the ReleaseFailedException constructor expects a String:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':release'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        ...
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: pl.allegro.tech.build.axion.release.ReleaseFailedException(java.util.Optional)
        at pl.allegro.tech.build.axion.release.ReleaseTask.release(ReleaseTask.groovy:26)
```

**Comment by adamdubiel** [comment]
Argh, dynamic languages ;) Obviously needs to be fixed. Test is at GitRepository level in `RemoteRejectionTest`.

**Comment by cliffred** [comment]
I'll try to create a pull request soon.

**Comment by cliffred** [comment]
If a message is absent, should it be an empty message, or something like 'Unkown error'?

**Comment by adamdubiel** [comment]
I would go for unknown.
