### ISSUE TITLE
In default, properties.directory will be set to folder "${rootDir}.config", then error occurs

### ISSUE THREAD

**Issue by andy837** [allegro/axion-release-plugin#231]
https://github.com/allegro/axion-release-plugin/blob/caf3666a30ff752b4d92933ee07484505106595b/src/main/groovy/pl/allegro/tech/build/axion/release/infrastructure/git/GitRepository.groovy#L34

I wrote below script into build.gradle
    scmVersion {
           tag {
               prefix = 'xxxxxxx'
           }
     }
    project.version = scmVersion.version
When I run command 'gradle release', then got error, 
    error: ${rootDir}/config (Is a directory)
After I add below script(repository.directory) to build.gradle, then error gone
    scmVersion {
           tag {
               prefix = 'xxxxxxx'
           }
           repository {
    	       directory = project.rootProject.file('../')
           }
      }
     project.version = scmVersion.version
Then I view this plugin code, I found this plugin take folder "${rootDir}/config" as a default repository.directory, hope this info can help you to fix the issue

**Comment by adamdubiel** [comment]
I'm not sure i understand the problem. As you can see [here](https://github.com/allegro/axion-release-plugin/blob/1b5ac3ff3fc26afd48ca47ef5426c4f666beaad8/src/main/groovy/pl/allegro/tech/build/axion/release/domain/RepositoryConfigFactory.groovy#L21) the default value of `scmConfig.repository.directory` is `project.rootDir`. What is the root dir in your project (the one with `build.gradle` and `settings.gradle`)?

**Comment by andy837** [comment]
Hi, I'm sure my project.rootDir is correct, below is my code 

`plugins {
    id 'pl.allegro.tech.build.axion-release' version '1.9.0'
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

sourceCompatibility = JavaVersion.VERSION_1_6
targetCompatibility = JavaVersion.VERSION_1_6

task wrapper(type: Wrapper) {
	gradleVersion = '4.6'
}

scmVersion {
    tag {
        prefix = 'xxxxxx'
    }
    
    repository {
    	directory = project.rootProject.file('../')
    }
}

version = scmVersion.version`
.........

When I didn't add 'scmVersion.repository.directory', then the 'scmConfig.repository.directory' is ${project.rootDir}/config, when I added 'scmVersion.repository,directory', then 'scmConfig.repository.directory' is project.rootDir

**Comment by adamdubiel** [comment]
Can you show your project dir structure? What is this `config` directory?

**Comment by andy837** [comment]
Folder config just include checkstyle config files, below is the error info

````
$ gradle release --stacktrace
Listening for transport dt_socket at address: 9998
:verifyRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':verifyRelease'.
> java.io.FileNotFoundException: project.rootDir\config (Is a directory)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':verifyRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: project.rootDir\config (Is a directory)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: java.io.FileNotFoundException: project.rootDir\config (Is a directory)
        at org.eclipse.jgit.util.IO.readFully(IO.java:141)
        at org.eclipse.jgit.util.IO.readFully(IO.java:81)
        at org.eclipse.jgit.storage.file.FileBasedConfig.load(FileBasedConfig.java:147)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.loadConfig(BaseRepositoryBuilder.java:719)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.getConfig(BaseRepositoryBuilder.java:696)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.guessWorkTreeOrFail(BaseRepositoryBuilder.java:732)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.setupWorkTree(BaseRepositoryBuilder.java:662)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:589)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:612)
        at org.eclipse.jgit.api.Git.open(Git.java:122)
        at org.eclipse.jgit.api.Git.open(Git.java:102)
        at org.eclipse.jgit.api.Git$open.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.<init>(GitRepository.groovy:34)
        at pl.allegro.tech.build.axion.release.infrastructure.di.ScmRepositoryFactory.create(ScmRepositoryFactory.groovy:23)
        at pl.allegro.tech.build.axion.release.infrastructure.di.ScmRepositoryFactory$create.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.infrastructure.di.GradleAwareContext.create(GradleAwareContext.groovy:15)
        at pl.allegro.tech.build.axion.release.infrastructure.di.GradleAwareContext$create$1.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.VerifyReleaseTask.verify(VerifyReleaseTask.groovy:23)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 42 more

````

I think the key point is not here, as you say, the default value of scmConfig.repository.directory is project.rootDir, the key point is scmConfig.repository.directory or project.rootDir, but I wrote a task to print project.rootDir, the result has prove project.rootDir is correct

**Comment by andy837** [comment]
Sorry adamdubiel, I just replace the real dir with  'project.rootDir' to comply the company policy (cry face)

**Comment by andy837** [comment]
Hi Adamdubiel, as you say, I created a new gradle project(it has same folder config), although I delete configuration 'scmConfig.repository.directory', it also work fine, but I have no idea why my old project can't work, it seems the old project has different configuration cause the project.rootDir be changed

**Comment by andy837** [comment]
Hi Adamdubiel, it seems only one [place](https://github.com/allegro/axion-release-plugin/blob/1b5ac3ff3fc26afd48ca47ef5426c4f666beaad8/src/main/groovy/pl/allegro/tech/build/axion/release/domain/RepositoryConfigFactory.groovy#L21) the scmVersion.repository be initialized, but I wrote a task to print project.rootDir, the result is correct, so I have no idea where project.rootDir be changed, maybe in running env....

**Comment by adamdubiel** [comment]
How about you create a task that prints `scmVersion.repository.directory`? This flag can be only set using configuration, it is never read from cmd line nor env.

**Comment by adamdubiel** [comment]
Did you manage to get it right? What was the problem?

**Comment by adamdubiel** [comment]
I'm closing this one for now - if you found a solution or need more help don't hesitate to reopen :)
