### ISSUE TITLE
NPE on pushing changes to GitHub with GH_TOKEN

### ISSUE THREAD

**Issue by szpak** [allegro/axion-release-plugin#32]
An alternative way to push changes to GitHub (useful especially from CI server) is the usage of personal access token. Unfortunately it fails with NPE from jgit.

```
Caused by: java.lang.NullPointerException
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:476)
	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:396)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:154)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1173)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:79)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.push(GitRepository.groovy:80)
	at pl.allegro.tech.build.axion.release.domain.scm.ScmRepository$push$5.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.domain.Releaser.release(Releaser.groovy:42)
	at pl.allegro.tech.build.axion.release.domain.Releaser$release.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.ReleaseTask.release(ReleaseTask.groovy:40)
(...)
```

I debugged it briefly and GH returns 401 on the first connection try and in the second attempt it does not have a credential provider which causes NPE. In jgit master they modified code and more verbose TransportException would be probably [throw](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/transport/TransportHttp.java#L497).

I din't dig into that, but the connection URI is:
```
https://my-very-long-token@github.com/foo/bar.git/info/refs?service=git-receive-pack
```

which returns 401 (Unathorized). After change it (in debuger) to just `https://my-very-long-token@github.com/foo/bar.git/` it returns 200, but later fails on `NotSupportedException: remote does not support smart HTTP push`.

Steps to reproduce:
1. Checkout any project with Axion configured from GH.
2. Change remote url to url = https://${YOUR_GH_TOKEN}@github.com/you/your-project.git
3. Call `./gradlew release`.

Btw, manual push with mentioned configuration works fine. Tested with Axion 0.9.9.

**Comment by adamdubiel** [comment]
I came to revisit this issue, as i had some need for Basic Auth/GitHub tokens :) I did not like passing GH Token via system variables (Grgit way), so i made own, simple implementation consistent with already present ssh keys supports. Usage is simple and straightforward:

```
./gradlew release -Prelease.customUsername=<myGithubCode>
```

Just be sure to checkout repository as `https://github.com/...`, without any codes inside. [Documentation](http://axion-release-plugin.readthedocs.org/en/development/configuration/authorization.html) is also present.

**Comment by szpak** [comment]
Sounds ok. Secure variables are masked in Travis and in addition probably `release.customPassword` could be also set within a build script (like `dryRun`).

**Comment by szpak** [comment]
BTw, you have a wrong milestone for that issues - `1.0.1`.

**Comment by adamdubiel** [comment]
Exactly, it can be set in runtime (see the docs).
