### ISSUE TITLE
Using commit hook causes release task to fail on Windows.

### ISSUE THREAD

**Issue by dbottstein** [allegro/axion-release-plugin#54]
`build.gradle` contains:

    scmVersion {
        hooks {
            pre 'fileUpdate', [...]
            pre 'commit'
        }
    }

Running `gradlew release` results in error:

    :verifyRelease
    Looking for uncommitted changes..
    Checking if branch is ahead of remote..
    :release
    Creating release commit
    :release FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':release'.
    > Illegal/unsupported escape sequence near index 3
      C:\Users\donb\src\myproject/
         ^
Stack trace:

    Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
    C:\Users\dboths001c\src\workflow\comcast-base/
       ^
        at java_lang_String$replaceFirst$3.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository$_commit_closure1.doCall(GitRepository.groovy:132)
        at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.commit(GitRepository.groovy:132)
        at pl.allegro.tech.build.axion.release.domain.scm.ScmRepository$commit$4.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.infrastructure.GradleAwareScmService.commit(GradleAwareScmService.groovy:35)
        at pl.allegro.tech.build.axion.release.domain.scm.ScmService$commit.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.domain.hooks.HookContext.commit(HookContext.groovy:32)
        at pl.allegro.tech.build.axion.release.domain.hooks.HookContext$commit$0.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.domain.hooks.CommitHookAction.act(CommitHookAction.groovy:18)
        at pl.allegro.tech.build.axion.release.domain.hooks.ReleaseHookAction$act.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.domain.hooks.ReleaseHookAction$act.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.domain.hooks.ReleaseHooksRunner$_runPreReleaseHooks_closure1.doCall(ReleaseHooksRunner.groovy:25)
        at pl.allegro.tech.build.axion.release.domain.hooks.ReleaseHooksRunner.runPreReleaseHooks(ReleaseHooksRunner.groovy:25)
        at pl.allegro.tech.build.axion.release.domain.hooks.ReleaseHooksRunner$runPreReleaseHooks.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.domain.Releaser.release(Releaser.groovy:41)
        at pl.allegro.tech.build.axion.release.domain.Releaser$release.call(Unknown Source)
        at pl.allegro.tech.build.axion.release.ReleaseTask.release(ReleaseTask.groovy:24)

Line 132 of GitRepository.groovy:

    repository.add(patterns: patterns.collect { it.replaceFirst(repositoryDir.canonicalPath + '/', '') })

**Comment by adamdubiel** [comment]
Thanks for the fix, ashamed to even make this kind of mistake :P
