### ISSUE TITLE
`release` fails with "Command org.eclipse.jgit.api.PushCommand was called in the wrong state"

### ISSUE THREAD

**Issue by big-andy-coates** [allegro/axion-release-plugin#573]
Hi,

I've been using your plugin across many projects without any issues for some time now - it's great!

However, I've one project from which I currently can't release, as it fails with:

```
Execution failed for task ':release'.
> Command org.eclipse.jgit.api.PushCommand was called in the wrong state
```

I'm calling `./gradlew` from a GibHub workflow.  This was previously working, but is now refusing to work, and stacktraces etc don't offer much in the way of information as to why.

I'd appreciate it if you have the time to help :)

Here's the log from [a run](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188) with stacktraces enabled:

```
Run # The following command will trigger the build.yml workflow as it pushes a release tag
  # The following command will trigger the build.yml workflow as it pushes a release tag
  ./gradlew release --stacktrace
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/16.0.[2](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:2)-7/x64
    JAVA_HOME_16_X64: /opt/hostedtoolcache/Java_Adopt_jdk/16.0.2-7/x64

> Task :verifyRelease
Looking for uncommitted changes.. 
Checking if branch is ahead of remote.. 
Checking for snapshot versions.. 

> Task :release FAILED
Creating tag: v0.[3](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:3).1
Pushing all to remote: origin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':release'.
> Command org.eclipse.jgit.api.PushCommand was called in the wrong state

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':release'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:1[4](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:4)2)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:[5](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:5)1)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:3[6](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:6))
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:[7](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:7)7)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:2[8](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:9)1)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:13[9](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:10))
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:[12](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:13)8)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:[15](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:16)7)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:3[22](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:23))
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:309)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:302)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:[28](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:29)8)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:462)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:[37](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:38)9)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:[49](https://github.com/specmesh/specmesh-build/actions/runs/4116851065/jobs/7107429188#step:7:50))


* Get more help at https://help.gradle.org/

BUILD FAILED in 2s
Error: Process completed with exit code 1.
```

And should you need it, there is [a run with debug turned on](https://github.com/specmesh/specmesh-build/actions/runs/4117048355) too.

**Comment by big-andy-coates** [comment]
Looksing at the code, it looks like the issue is coming from `GitRepository.java`:

```java
public ScmPushResult push(ScmIdentity identity, ScmPushOptions pushOptions, boolean all) {
        PushCommand command = pushCommand(identity, pushOptions.getRemote(), all);

        // command has to be called twice:
        // once for commits (only if needed)
        if (!pushOptions.isPushTagsOnly()) {
            ScmPushResult result = verifyPushResults(callPush(command));
            if (!result.isSuccess()) {
                return result;
            }

        }

        // and another time for tags
        return verifyPushResults(callPush(command.setPushTags()));
    }
```

It looks to me like if `isPushTagsOnly()` is `false` then the code is calling `call` on the push `command` twice. Yet, `PushCommand` looks like it can't be reused:

```java
@Override
	public Iterable<PushResult> call() throws GitAPIException,
			InvalidRemoteException,
			org.eclipse.jgit.api.errors.TransportException {
		checkCallable();
		setCallable(false);

```

...as its _always_ calling `setCallable(false)` when `call()` is executed.

**Comment by bgalek** [comment]
@big-andy-coates would you like to make an PR? :)

**Comment by big-andy-coates** [comment]
Yep, just checking the work around works (adding `-Prelease.pushTagsOnly`).

Will then raise PR.

Any idea why this has suddenly started failing? What else would it be trying to push?

**Comment by big-andy-coates** [comment]
The `setCallable(false);` in `PushCommmand.call` was introduced in `jgit` `6.1.0`.

The `com.diffplug.spotless` plugin is bringing in `jgit` `6.4.0`... hence the issue.

**Comment by bgalek** [comment]
I'm ok with ditching jdk8 & bumping minor version

**Comment by big-andy-coates** [comment]
I think ditching j8 should be a major version bump personally, but up to you :)

**Comment by big-andy-coates** [comment]
I've raised a PR to fix the immediate issue, though I can't write a test on J8...
