### ISSUE TITLE
Release not working in Jenkins - Push fails with message "Nothing to push"

### ISSUE THREAD

**Issue by joergus** [allegro/axion-release-plugin#66]
Executing `gradle release` via Jenkins is not working for me. I'm using gradle 2.3 and the jenkins git plugin 2.3.5. 

I can reproduce that on a development machine when executing a checkout of a certain revision as it is done by jenkins `git checkout -f eced05a5302fa1bc452f57d3accc504965157344`.
I'm using the default git plugin.
The Exception is the following.
```
:release
Executing task ':release' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
Working on released version 0.3.2, nothing to release.
Pushing all to remote: origin
The following authentication options are allowed (though they may not be available): [HARDCODED, SSHAGENT, PAGEANT, INTERACTIVE]
:release FAILED
:release (Thread[main,5,main]) completed. Took 0.478 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':release'.
> Problem pushing to remote.

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':release'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.ajoberstar.grgit.exception.GrgitException: Problem pushing to remote.
	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy:117)
	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
	at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:175)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.callPush(GitRepository.groovy:80)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.push(GitRepository.groovy:76)
	at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.push(GitRepository.groovy:72)
	at pl.allegro.tech.build.axion.release.domain.scm.ScmRepository$push$2.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.infrastructure.GradleAwareScmService.push(GradleAwareScmService.groovy:30)
	at pl.allegro.tech.build.axion.release.domain.scm.ScmService$push$0.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.domain.Releaser.pushRelease(Releaser.groovy:54)
	at pl.allegro.tech.build.axion.release.domain.Releaser$pushRelease$1.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.ReleaseTask.release(ReleaseTask.groovy:16)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 44 more
Caused by: org.eclipse.jgit.api.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:160)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:79)
	at java_util_concurrent_Callable$call$0.call(Unknown Source)
	at org.ajoberstar.grgit.operation.PushOp.call(PushOp.groovy:114)
	... 66 more
Caused by: org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1197)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:156)
	... 69 more
```

Any ideas to get around that, or is there a fix required?

**Comment by adamdubiel** [comment]
The commit that you check out - is it tagged commit? I did some testing with Jenkins ([here](http://axion-release-plugin.readthedocs.org/en/latest/configuration/ci_servers.html#jenkins)) and it seemed to work out of box.

**Comment by joergus** [comment]
No. I define, e.g. "develop" as branch to build, but what the git plugin does is the following
```
git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@git.raysono.int:joergw/gradle-release-test.git # timeout=10
Fetching upstream changes from git@git.raysono.int:joergw/gradle-release-test.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress git@git.raysono.int:joergw/gradle-release-test.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/develop^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/develop^{commit} # timeout=10
Checking out Revision eced05a5302fa1bc452f57d3accc504965157344 (refs/remotes/origin/develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f eced05a5302fa1bc452f57d3accc504965157344
 > git rev-list eced05a5302fa1bc452f57d3accc504965157344 # timeout=10
[Gradle-Release-Test] $ /bin/sh -xe /opt/apache-tomcat-7.0.32/temp/hudson2755502484777300746.sh
+ git status
# Not currently on any branch.
```
The Git status is from an extra shell call. 
And if I execute the _git checkout -f_ on my local machine, I'm running into same issue as Mister Jenkins does.

**Comment by adamdubiel** [comment]
Hm, but if you are in detatched state, there is no way git will push anything to upstream (since there is no upstream). Can you show me how git pull is configured in your build in Jenkins?

**Comment by joergus** [comment]
Configuration looks like the following.

![gradle-release-test config jenkins _2015-04-20_15-29-50](https://cloud.githubusercontent.com/assets/443874/7230952/45479642-e772-11e4-8b87-7412c7a61a53.png)

**Comment by adamdubiel** [comment]
Sorry for no response -  it has been a bit busy time for me. I guess it's closely related to another issue, #68. I'm not using Jenkins on daily basis (installed it to check out how axion is doing and worked fine for me), so i might not be able to help without your assistance.

axion-relese needs two things in git repository to function properly:
* previous tags (i.e. Bamboo CI does not fetch them by default)
* being on a branch (not detached state) - otherwise it is impossible to create release

I'm not sure how to achieve them on Jenkins.

**Comment by joergus** [comment]
Today i tried a config mentioned in https://issues.jenkins-ci.org/browse/JENKINS-6856 that addresses that issue too. I suppose it should work to specifiy a target local branch in config, but unfortunately I cannot verify that, because I'm till now not able to get some other issues solved within the communitcation of jenkins and git. 
```
Caused by: org.eclipse.jgit.errors.TransportException: git@--------:joergw/gradle-release-test.git: UnknownHostKey: xxx.xxxxx.xxxx. RSA key fingerprint is ac:26:8b:bb:f6:2e:fe:62:83:37:1e:4b:b9:db:08:ae
```
Via command line everything works fine :(
I try to verify the solution the next days.

**Comment by adamdubiel** [comment]
Remember, that JGit manages keystore by itself. It's not 1:1 to command line. This is source of some strange bugs at times - maybe this is it?

**Comment by joergus** [comment]
Okay, the configuration is working as expected. If you specify an _Additional Behaviours_ - _Check out to specific local branch_ in Jenkins GIT Project configuration, everything is working fine.
![gradle-release-test config jenkins _2015-05-13_10-58-44](https://cloud.githubusercontent.com/assets/443874/7607161/7e7aefb4-f95f-11e4-9dd1-5b6cbec2ca34.png)

**Comment by adamdubiel** [comment]
Thanks for the tip, i will leave it open until i change it in documentation :)

**Comment by erichsend** [comment]
The workaround presented here does not work for my purposes. Due to how my git repositories are hosted and how builds are kicked off in Jenkins, my jenkins service is sometimes checking out a branch and other times in a detached head state.

To get around this, I had to make a code change to the axion plugin such that it will only attempt to push tags to the remote repo, which is allowable in a detached head state. The flag to configure this behavior is on the repository config object  `repository.pushTagsOnly`.

**Comment by adamdubiel** [comment]
`1.3.0` version with your change, @erichsend has been released. Sorry it took so long :) Now i can close this issue as well.
