### ISSUE TITLE
UnexpectedCharacterException when using with Jenkins

### ISSUE THREAD

**Issue by szpak** [allegro/axion-release-plugin#67]
A job created with default configuration for Git fails with 
> com.github.zafarkhaja.semver.UnexpectedCharacterException (no error message)

After some digging it seems that Axion takes also non matching tags to pass it to semver when on a tag. Jenkins in turn creates `jenkins-job-name-X` when cloning project from a repo.

Tested with Axion 1.2.0 and 1.2.3.

Steps to reproduce.
```
git clone https://github.com/Codearte/gradle-nexus-staging-plugin.git #or anything else with Axion
./gradlew cV               #works fine
git tag jenkins-foo-5
./gradlew cV               #exception
```

Longer stacktrace:
```
* What went wrong:
A problem occurred evaluating root project 'gradle-nexus-staging-plugin'.
> com.github.zafarkhaja.semver.UnexpectedCharacterException (no error message)
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'gradle-nexus-staging-plugin'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
(...)
Caused by: Unexpected character 'LETTER(j)' at position '0', expecting '[DIGIT]'
	at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
	at com.github.zafarkhaja.semver.VersionParser.digits(VersionParser.java:448)
	at com.github.zafarkhaja.semver.VersionParser.numericIdentifier(VersionParser.java:408)
	at com.github.zafarkhaja.semver.VersionParser.parseVersionCore(VersionParser.java:285)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:255)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
	at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)
	at com.github.zafarkhaja.semver.Version$valueOf.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at pl.allegro.tech.build.axion.release.domain.VersionFactory.create(VersionFactory.groovy:17)
	at pl.allegro.tech.build.axion.release.domain.VersionFactory$create.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at pl.allegro.tech.build.axion.release.domain.VersionResolver.resolveVersion(VersionResolver.groovy:21)
	at pl.allegro.tech.build.axion.release.domain.VersionResolver$resolveVersion.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at pl.allegro.tech.build.axion.release.domain.VersionService.currentDecoratedVersion(VersionService.groovy:34)
	at pl.allegro.tech.build.axion.release.domain.VersionService$currentDecoratedVersion.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at pl.allegro.tech.build.axion.release.domain.VersionConfig.getVersion(VersionConfig.groovy:91)
	at pl.allegro.tech.build.axion.release.domain.VersionConfig_Decorated.getVersion(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:60)
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:153)
	at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:107)
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:78)
	at pl.allegro.tech.build.axion.release.domain.VersionConfig_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
	at build_cxczvsypzye5vt7n1iyqd57kg.run(/tmp/gradle-nexus-staging-plugin/build.gradle:28)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 45 more
```

**Comment by szpak** [comment]
Btw, as a workaround am additional Git plugin behavior "Create a tag for every build" can be disabled.

**Comment by szpak** [comment]
Btw2, that configuration is probably "default" only when [Job DSL Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin) is used to generate new tasks.

**Comment by adamdubiel** [comment]
AFAIR you don't use any prefix to prefix your version tags? Scanning for version tags is quite simple - it looks up tags with matching prefixes and tries to interpret them. Since your prefix is `""` (empty string), every tag matches. This leads to exception when trying to parse it.

**Comment by szpak** [comment]
In the end I changed a tag format to `release/0.2.45`. With "/" (instead "-") it is even easier to detect changes with given refspec (and for example build only release tags).

I don't know if there is sense to implement checking if tag starts with something compliant with semver, so for me it would be ok to close this issue.

**Comment by adamdubiel** [comment]
I had few requests to implement either semver-checking or at least wrap it in some nicer exception - now this tells nothing. But there is a seperate issue related with this (#61), so i will close this one.
