### ISSUE TITLE
On GitHub Actions an error on creating a jgit lock file appears

### ISSUE THREAD

**Issue by Zordid** [allegro/axion-release-plugin#730]
On any step involving the axion-release-plugin (currentVersion, release, etc) I get this error on my GitHub action run:

```
Creating lock file $HOME/.config/jgit/config.lock failed
java.nio.file.NoSuchFileException: $HOME/.config/jgit/config.lock
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.createFile(Files.java:648)
	at org.eclipse.jgit.util.FS_POSIX.createNewFileAtomic(FS_POSIX.java:429)
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:146)
	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:201)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:776)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$5(FS.java:458)
        [...]
Cannot save config file 'FileBasedConfig[$HOME/.config/jgit/config]'
java.nio.file.NoSuchFileException: $HOME/.config/jgit/config.lock
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.createFile(Files.java:648)
	at org.eclipse.jgit.util.FS_POSIX.createNewFileAtomic(FS_POSIX.java:429)
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:146)
	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:201)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:776)
	at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$5(FS.java:458)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I really do not find anything on such issues searching the web, but it must be related to this plugin as normal `build` tasks just run fine.

Do you have any idea?

Using latest 1.17.0 version! Thanks!

**Comment by bgalek** [comment]
I couldn't reproduce this issue, do you think you could provide a small repo with this issue?
