### ISSUE TITLE
Git repository added as submodules do not work

### ISSUE THREAD

**Issue by sirish-bajpai** [allegro/axion-release-plugin#734]
If I add a Git repository as a submodule to a parent Git repo using:
`git submodule add http://<dependent-repo-url>`

then the plugin in dependent-repo fails with exception stack trace:
```
Failed to open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /<path-to-dependent-repo-dir>
Couldn't perform is legacy DefTagname Repository command on uninitialized repository
Could not resolve current position on uninitialized repository, returning default
Could not resolve current position on uninitialized repository, returning default
Couldn't perform check uncommitted changes command on uninitialized repository
/home/sbajpai/Projects/Carematix/CM-ReportGenerator/chartservice/.git/config: Not a directory
java.nio.file.FileSystemException: /home/sbajpai/Projects/Carematix/CM-ReportGenerator/chartservice/.git/config: Not a directory
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
.....
```
Basically in a submodule repo .git is a file with pointer to parent, instead of a directory, causing plugin to fail and assume initial version instead of tagged version.

**Comment by bgalek** [comment]
Hi! Yeah, we don't have natvice submodule support

**Comment by SonarSonic** [comment]
Also just encountered the same issue, any known workarounds?
