### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by matyasatfp** [allegro/axion-release-plugin#87]
Build fails on Windows because of a bug in JGit, this the the stack trace:   
                               
JGit developers fixed it, you just need to upgrade the version you are using https://github.com/eclipse/jgit/commit/ec6ec3b10fb1ef8dd73a499d0b1f7a7d711b84dd

the stack trace:

    Caught exception in FS.readPipe()
    java.io.IOException: Cannot run program "bash" (in directory "C:\Users\myAccount"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at org.eclipse.jgit.util.FS.readPipe(FS.java:431)
        at org.eclipse.jgit.util.FS_Win32.discoverGitPrefix(FS_Win32.java:113)
        at org.eclipse.jgit.util.FS.gitPrefix(FS.java:517)
        at org.eclipse.jgit.util.SystemReader$Default.openSystemConfig(SystemReader.java:92)
        at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:171)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:577)
        at org.eclipse.jgit.api.Git.open(Git.java:113)
        at org.eclipse.jgit.api.Git.open(Git.java:97)
        at org.eclipse.jgit.api.Git$open.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:59)
        at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.ajoberstar.grgit.Grgit$__clinit__closure1.doCall(Grgit.groovy:180)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
        at groovy.lang.Closure.call(Closure.java:423)
        at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:59)
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1492)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1480)
        at groovy.lang.ExpandoMetaClass.invokeStaticMethod(ExpandoMetaClass.java:1129)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at pl.allegro.tech.build.axion.release.infrastructure.git.GitRepository.<init>(GitRepository.groovy:34)
    ...

**Comment by matyasatfp** [comment]
Edit, I just realized that I dont have git in PATH, the JGit bug is just about emitting the wrong error message.

**Comment by adamdubiel** [comment]
Okay :)

**Comment by svverma** [comment]
I am getting the above issue but I dont have jgit in my system. I am simply trying to execute a task inside build.gradle using command line and getting the above issue. Can anyone help

**Comment by adamdubiel** [comment]
`jgit` is a library downloaded from Maven Central by buildscript, so you don't need to have it anywhere. From what i understand though (i'm not a windows user), you should have Git installed and available via cmd line.

**Comment by svverma** [comment]
But I already have Git on in my system and I am running the commands through command prompt. Any other thing I might be missing ?

**Comment by svverma** [comment]
It seems there is some issue with Windows 10. I ran the commands by running cmd prompt as admin, it is running the commands successfully and cloning the repository.

**Comment by adamdubiel** [comment]
Hm, i'm sorry but i have no access to Windows 10, what you mean is that axion-release works when you run it with admin privileges?

**Comment by svverma** [comment]
See, this is how I am running the command to clone a repository from GitHub
to a local repository. I was getting that error after the command 'gradlew
cloneTest'. Now, I am able to get that repo in the local repo but its not
synced as in it is showing the red symbol and not the green one.

**Comment by adamdubiel** [comment]
No attachment here :) I guess it was lost in translation. Still, does it have anything to do with `axion-release`?

**Comment by svverma** [comment]
No, nothing to do with axion-release.

**Comment by adamdubiel** [comment]
Okay, since it's JGit issue maybe you should try your luck at JGit forums? There might be more people using JGit on Windows 10.

**Comment by svverma** [comment]
okay, Thanks
