### ISSUE TITLE
Cannot filter Version (1.0.0.0) from Tag 

### ISSUE THREAD

**Issue by rongo89** [allegro/axion-release-plugin#96]
Hey

i have a problem while trying to filter out the version from a tag with the format "ProjectName_1.0.0.0".

My Stacktrace:

```
./gradlew --stracktrace cV
```

```javascript

Caused by: Unexpected character 'DOT(.)' at position '5', expecting '[HYPHEN, PLUS, EOI]'
	at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:259)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
	at com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)
	at com.github.zafarkhaja.semver.Version$valueOf.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.domain.VersionFactory.create(VersionFactory.groovy:17)
	at pl.allegro.tech.build.axion.release.domain.VersionFactory$create.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.domain.VersionResolver.resolveVersion(VersionResolver.groovy:21)
	at pl.allegro.tech.build.axion.release.domain.VersionResolver$resolveVersion.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.domain.VersionService.currentDecoratedVersion(VersionService.groovy:30)
	at pl.allegro.tech.build.axion.release.domain.VersionService$currentDecoratedVersion.call(Unknown Source)
	at pl.allegro.tech.build.axion.release.domain.VersionConfig.getVersion(VersionConfig.groovy:108)
	at pl.allegro.tech.build.axion.release.domain.VersionConfig_Decorated.getVersion(Unknown Source)
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:153)
	at org.gradle.api.internal.BeanDynamicObject.getProperty(BeanDynamicObject.java:107)
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:78)
	at pl.allegro.tech.build.axion.release.domain.VersionConfig_Decorated.getProperty(Unknown Source)

```

And here is my configuration from build.gradle

```javascript
scmVersion {
    repository {
        type = 'git'
        directory = project.rootProject.file('../../../')
        remote = 'origin'
        }

        localOnly = true

    tag {
    	prefix = 'ProjectName'
    	versionSeparator = '_'
        
    }

    nextVersion {
        suffix = 'ProjectName'
        separator = '_' // separator between version and suffix
    }
}

version = scmVersion.version

```

Is this a bug or did I miss something ?

Thanks for help

**Comment by adamdubiel** [comment]
The format you are using does not match SemVer. Versions should look like `1.0.0-rc` or `1.0.0+build` (you can read more [here](http://semver.org/)).

**Comment by rongo89** [comment]
thanks for advice. its a company internal format, so we have to reconsider it apparently.
